### ISSUE TITLE
Search function is not available

### ISSUE THREAD

**Issue by bequt** [azmelanar/hugo-theme-pixyll#11]
Search function is not available, what's the cause? Github domain name is not used to separate domain names.

**Comment by azmelanar** [comment]
Hi @bequt,

We are working on #17 to describe how search works. I will update this issue as soon as it will be merged.

Thanks

Cheers,
azmelanar

**Comment by azmelanar** [comment]
Hi @bequt, 

PR is merged, how to work with search you can check in readme (search section):

https://github.com/azmelanar/hugo-theme-pixyll#search

Thanks

Cheers,
azmelanar
