### ISSUE TITLE
Please add a thumbnail

### ISSUE THREAD

**Issue by digitalcraftsman** [azmelanar/hugo-theme-pixyll#16]
Hello @azmelanar,

currently, the theme site shows a blank image where the thumbnail for your theme is supposed to be. Please (re)add a thumbnail as described [here](https://github.com/gohugoio/hugoThemes#media).

Cheers,
Digitalcraftsman

**Comment by azmelanar** [comment]
Hi @digitalcraftsman,

Added.

Cheers,
azmelanar

**Comment by digitalcraftsman** [comment]
Thanks @azmelanar :+1:
