### ISSUE TITLE
Add to hugoThemes?

### ISSUE THREAD

**Issue by chibicode** [azmelanar/hugo-theme-pixyll#2]
I'd love to see this on the official hugoThemes page:
https://github.com/spf13/hugoThemes/

Here are the instructions:
https://github.com/spf13/hugoThemes/#adding-a-theme-to-the-list

**Comment by azmelanar** [comment]
Created pull request [#24](https://github.com/spf13/hugoThemes/pull/24), waiting for merge.

**Comment by chibicode** [comment]
Thanks!

**Comment by chibicode** [comment]
It's now added :) Thank you!
