### ISSUE TITLE
syntax for multiple tags?

### ISSUE THREAD

**Issue by vajlex** [azmelanar/hugo-theme-pixyll#23]
hello, for the yaml header of each markdown post, I see the example of tags = ["futurama"]
can I guess that this will work for multiple tags:
tags =["futurama","simpsons"]
is that correct?  thanks!

this is seen in the example:  
https://raw.githubusercontent.com/azmelanar/hugo-theme-pixyll/master/theme.toml

but I can't understand, are we supposed to hard-code ALL possible tags in the theme.toml?

I tried a few tags in that theme.toml and matched them in my post tags, then re-run the create_json.py, but even though the pages are formatted with tag links, the pages do not resolved to anything, like:

site-root/tags/tagname

can you help?

**Comment by vajlex** [comment]
or is it:

tags = ["futurama, simpsons"]

?

**Comment by kshcherban** [comment]
Example of tags
```
tags = ["android", "linux", "root", "adblocker"] 
```

**Comment by vajlex** [comment]
thanks for your reply, I started using that syntax, but I don't get any page that serves the tags, for example:
https://maps.cga.harvard.edu/cga-legacy/tags/grants/
https://maps.cga.harvard.edu/cga-legacy/tags/DCE%20-%20FAS

those are tags on the pages:
http://maps.cga.harvard.edu/cga-legacy/post/2015-03-20-china-historical-gis/
https://maps.cga.harvard.edu/cga-legacy/post/2018-01-24-introduction-gis-course-critical-analysis-environmental/

thanks

**Comment by kshcherban** [comment]
Here's our working blog configuration (https://www.prolinux.org/tags/). However second language tags have issue.
part of config.toml
```
[indexes]
  category = "categories"
  tag = "tags"
  search = "search"
```
archetypes/default.md
```
+++
title = ""
author = ""
draft = true
tags = [""]
date = {{ .Date }}
+++
```
Please check that, maybe you are missing something. Also we use hugo version v0.40.3 
You can check this docker container:
https://hub.docker.com/r/bamaboy/docker-hugo-awscli/

**Comment by vajlex** [comment]
hi,  thanks for your reply.  I noticed in archetype the file had tags = []  so I changed it.  currently the sections in config.toml and defaul.md are the same as yours.   But even though the tags are generated for the content, when clicking on the tag link, there is only and index.xml file in the folders.... ?
https://maps.cga.harvard.edu/cga-legacy/tags/
Not sure why the tag "pages" are not being generated.  
Also, I noticed some of the links to pages are not working, maybed I need to set canonifyURLS = false?
Appreciate your tips on this.   I might switch back to HEXO for now, owing to deadline issue.

**Comment by azmelanar** [comment]
Hi! Please check [Taxonomies](https://gohugo.io/content-management/taxonomies/) documentation of Hugo (they use `taxonomies` rather than `indexes`), maybe it could be affected by latest version of Hugo. I will close issue for now. Please open new one, if we could somehow help you with it. Thanks
