### ISSUE TITLE
Add screenshot and thumbnail

### ISSUE THREAD

**Issue by bep** [azmelanar/hugo-theme-pixyll#3]
We are setting up themes.gohugo.io - and the themes must have some common metadata/images.

Could you have a look at 

https://github.com/spf13/hugoThemes

And fill the missing pieces - I had a quick look, and a screenshot.png and tn.png should do most of the trick.

Great theme.

**Comment by digitalcraftsman** [comment]
Don't forget to update you README.

**Comment by kshcherban** [comment]
Already added screenshot. Resolving.
