### ISSUE TITLE
Tipue Search isn't working on https://themes.gohugo.io/pixyll/

### ISSUE THREAD

**Issue by inspiredlabs** [azmelanar/hugo-theme-pixyll#31]
Comparing search options for HUGO I came across this theme. Tipue Search requires `https://code.jquery.com/jquery-3.3.1.min.js` for a working demo, would it be worth including it so people don't have to download the theme and configure it themselves?

**Comment by kshcherban** [comment]
Thanks, but jquery should be already included here
https://github.com/azmelanar/hugo-theme-pixyll/blob/master/layouts/_default/terms.html#L11

**Comment by kshcherban** [comment]
@inspiredlabs Tipue Search isn't working in demo because demo didn't generate search index with helper script.
https://themes.gohugo.io//theme/pixyll//tipuesearch/tipuesearch_content.js not found.

**Comment by azmelanar** [comment]
I will close this issue. Please refer to @kshcherban comment. Thanks
