### ISSUE TITLE
Tags Page No Longer Works

### ISSUE THREAD

**Issue by kpatel28** [azmelanar/hugo-theme-pixyll#33]
I noticed that the tags page on my blog no longer functions. Clicking on a tag and going to the tag page lists all the pages on the blog (no filtering). I think this has something to do with the changes made to comply with Hugo v.57 (Pages->RegularPages). I have some familiarity with how hugo works, but I'm still a beginner and can't figure out how to filter RegularPages by whether or not they have a tag.

**Comment by ghostiam** [comment]
Just replace in https://github.com/azmelanar/hugo-theme-pixyll/blob/master/layouts/tag/tag.html#L8
`.Site.RegularPages.ByDate.Reverse`
to
`.Data.Pages.ByDate.Reverse`

**Comment by kpatel28** [comment]
> Just replace in https://github.com/azmelanar/hugo-theme-pixyll/blob/master/layouts/tag/tag.html#L8
> `.Site.RegularPages.ByDate.Reverse`
> to
> `.Data.Pages.ByDate.Reverse`

That works locally but for some reason fails on gitlab pages on a 404 error. The fact that it works locally makes me think this is a permissions problem.
Are there any special permissions to set that you know of? I tried changing the permission of the tag.html template from 644 to 777, but even that didn't fix it.

Thanks for your help. If you don't know then I will close the issue promptly and try to fix it on my own.
