### ISSUE TITLE
Jekyll-syntax

### ISSUE THREAD

**Issue by bep** [azmelanar/hugo-theme-pixyll#4]
The templates contains a lot of Jekyll-syntax that doesn't work with Hugo.

**Comment by kshcherban** [comment]
I see only [pagination.html](https://github.com/azmelanar/hugo-theme-pixyll/blob/master/layouts/partials/pagination.html) with Jekyll-syntax but at the time of writing theme pagination was not supported in hugo.
Can you please point me to any other files with Jekyll-syntax?

**Comment by bep** [comment]
Maybe it was only that .. I just saw a lot of errors while generating the new Hugo theme site ... A simple "grep {%" should give you an indication.

**Comment by kshcherban** [comment]
Added pagination support and removed Jekyll syntax.
