### ISSUE TITLE
Problem with tags page

### ISSUE THREAD

**Issue by dallascard** [azmelanar/hugo-theme-pixyll#47]
I am new to Hugo, so this may be due to a lack of knowledge on my part, but I am having a problem with the Tags page using this (otherwise wonderful) template. 

My baseURL is `https://<username>.github.io/<project>/`

In my config file I also have

```
indexes:
    tag = "tags"
```

Tags on posts and on the home page work perfectly, as they go to:
`https://<username>.github.io/<project>/tags/<tag>`

However, if I go to the Tags page, all of the links from there are missing the `<project>` part of the urls, so that they point to:
`https://<username>.github.io/tags/<tag>`
and therefore point to non-existent pages.

My hugo version is 0.88.1+extended, and I get the same behaviour both locally and when hosted on Github.

Is there a way to get the links from the Tags page to work properly?

**Comment by azmelanar** [comment]
Hi,

Currently it's a way how we render link for each tag on Tags page:

https://github.com/azmelanar/hugo-theme-pixyll/blob/master/layouts/tag/tag.html#L9

Tried to change it to something like:

```
{{ .Site.Params.baseUrl }}{{ $.Site.LanguagePrefix }}/tags/{{ .LinkTitle }}
```

But don't work for me :( Also, not sure if `.LinkTitle` is the best option there.

If you have any ideas how to change it, just let me know.

Thanks

**Comment by dallascard** [comment]
Thanks! I also had a look at `tag.html`, but I think that actually controls the page for each individual tag, (e.g.,  `<domain>/<project>/tags/<tag>`), and those actually work fine! 

The problem is with the links on the overall Tags page (e.g., `<domain>/<project>/tags/`). I couldn't find where that page is being generated by this theme, which makes me think maybe it's part of the base hugo code? Unfortunately I don't know enough yet, but I will keep looking!
