### ISSUE TITLE
How to build combined-min.css?

### ISSUE THREAD

**Issue by radious** [azmelanar/hugo-theme-pixyll#9]
I'm trying to tweak css files but it seems that static/css/combined-min.css is not a combination of included css files (I tried compressing them in different orders with yuicompressor). 
Could you please share how is it built?
Thanks!

**Comment by kshcherban** [comment]
[This](http://fonts.googleapis.com/css?family=Ubuntu:400,700,400italic,700italic&subset=latin,cyrillic-ext,cyrillic) was added to combined-min.css too.
Check https://github.com/azmelanar/hugo-theme-pixyll/blob/b9e6081/layouts/partials/head.html
